export { default as HomeView } from "./Home";
export { default as FavoritesView } from "./Favorites";
export { default as CouponsView } from "./Coupons";
export { default as AddressView } from "./Address";
export { default as PaymentView } from "./Payment";
export { default as HistoricalsView } from "./Historicals";
export { default as SignInModal } from "./SignIn";
export { default as ConfigView} from "./Config";
export { default as CartView} from "./Cart";
export { default as DetailProduct} from "./DetailProduct";
export { default as AddEditCreditCardView} from "./AddEditCreditCard";